services:
  web:
    image: mcr.microsoft.com/dotnet/sdk:6.0     
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '5001:5001'
      - '7269:7269'
    volumes:
      - './app/src/:/app'
    working_dir: /app
    command: dotnet watch run

    depends_on:
      - db

  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: database_12345
    image: mcr.microsoft.com/mssql/server
    restart: always
